### ISSUE TITLE
passwd expiration time in UTC and not localtime

### ISSUE THREAD

**Issue by ll4strw** [stefan-wolfsheimer/irods_auth_pam_interactive#5]
I just noticed that `std::gmtime` in 

https://github.com/irods/irods_auth_plugin_pam_interactive/blob/9973475682c0833f5522c53ef4f523ee2492c9e5/src/pam_interactive.cpp#L200

makes my session expire as soon as I successfully log in via `iinit` without specifying a `ttl`. This occurs probably because I am located one hour ahead of UTC and  

https://github.com/irods/irods_auth_plugin_pam_interactive/blob/9973475682c0833f5522c53ef4f523ee2492c9e5/src/pam_interactive.cpp#L102

Would not be better to use 

`std::localtime(&expire)`? Thanks in advance, L.

**Comment by trel** [comment]
hmm, interesting.    we've generally used UTC and avoided timezones completely because they're hard and we always get them wrong.

but this use case is ... potentially compelling.    interesting that we're not consistent enough already that 3600 from 'now' doesn't calculate correctly.

**Comment by korydraughn** [comment]
I recommend explicitly setting the `ttl` value until we understand the problem more.

**Comment by trel** [comment]
good catch.   we'll test it out.

**Comment by korydraughn** [comment]
I'd prefer we not introduce handling of timezones. We have Boost which likely provides tools for working in UTC. The chrono library may have what we need already.

**Comment by alanking** [comment]
Nicely done, @ll4strw. Closing...
